language: java
sudo: true
dist: xenial
jdk: openjdk8

services:
  - docker

env:
  global:
    - GIT_HASH=$(git rev-parse HEAD)
    - DOCKER_IMAGE=konvio/kotlin-quarkus-graalvm

before_install:
  - chmod +x mvnw

script:
  - ./mvnw package -Pnative -Dnative-image.docker-build=true
  - docker build -f src/main/docker/Dockerfile.native -t $DOCKER_IMAGE .
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push $DOCKER_IMAGE